### ISSUE TITLE
Design the Processed Data Page

### ISSUE THREAD

**Issue by glenntanjoh** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#115]
**Tasks:**

- Develop wireframes to outline the basic structure and layout of the Processed Data Page.
- Consider user experience (UX) principles for easy navigation and information presentation.
- Create visual mockups that incorporate the BEAP Engine's existing design language.
- Ensure consistency with the overall application design.
- Define the elements on the Processed Data Page, including file display, download buttons, and any additional information.
- Ensure a clear and logical arrangement of elements for user comprehension.
- Choose a suitable colour scheme that aligns with the application's branding and promotes a user-friendly atmosphere.
- Select appropriate typography for readability and consistency.
- Design interactive elements for user-friendly interactions.
- Consider hover effects, click states, and other responsive behaviours.
- Implement a visually intuitive feedback mechanism for successful file downloads or any other user actions.
- Ensure error messages are clear and helpful.

**Considerations:**

- **Data Visualization:** Depending on the nature of the processed data, consider incorporating data visualization elements like graphs, charts, or tables for a more intuitive understanding of the data.
- **Pagination or Infinite Scroll:** If the amount of processed data is large, consider implementing pagination or infinite scroll to make data browsing more manageable.
- **Search and Filter Options:** These can help users find specific data more quickly and efficiently.
- **Responsive Design:** Ensure that the page layout and elements adapt well to different screen sizes and orientations.
- **Loading States:** Design and implement visually pleasing loading states for instances where data processing might take some time.
- **Accessibility:** Make sure all elements on the page are accessible to users with disabilities. This could involve using larger clickable areas for buttons, high-contrast colours for visibility, and keyboard navigation support.
- **Localization:** If your application will be used by people in different regions, consider how the Processed Data Page will support multiple languages or right-to-left scripts.

**Note:**

- Conduct usability testing with team members to gather feedback on the design.
- Iterate on the design based on the received feedback.
- The estimate for this is 4 days

**Comment by cameronbeattie306** [comment]
https://drive.google.com/file/d/1gc6KXq0wqwjZ_JHoFvclMqJI4VJFas4s/view?usp=sharing
