### ISSUE TITLE
Design the Navbar

### ISSUE THREAD

**Issue by glenntanjoh** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#117]
This task blocks #120 
**Task Breakdown:**

- Develop wireframes to outline the basic structure and layout of the Navbar component.
- Consider user experience (UX) principles for easy navigation and accessibility.
- Create visual mockups that incorporate the BEAP Engine's existing design language.
- Ensure consistency with the overall application design.
- Define the elements within the Navbar, including navigation links, user authentication buttons, and any additional features.
- Ensure a clear and logical arrangement of elements for intuitive user interaction.
- Choose a suitable colour scheme that aligns with the application's branding and promotes a user-friendly atmosphere.
- Select appropriate typography for readability and consistency.
- Design interactive elements for user-friendly interactions, such as highlighting active links or providing visual feedback on hover.
- Consider responsive behaviours for mobile and desktop views.
- Implement a visually intuitive feedback mechanism for successful interactions or any other user actions.
- Ensure error messages are clear and helpful.
- Collaborate with the team to ensure the feasibility of the proposed design.
- Address any technical constraints or considerations.
- Conduct usability testing with team members to gather feedback on the design.
- Iterate on the design based on the received feedback.

**Considerations:**

- **Accessibility:** Ensure that the Navbar is accessible to all users, including those with disabilities. This could involve using larger clickable areas for buttons, high-contrast colours for visibility, and keyboard navigation support.
- **Localization:** Assuming the application will be used by people in different regions, consider how the Navbar will support multiple languages or right-to-left scripts.
- **Scalability:** As the application grows, the Navbar might need to accommodate more items. Plan for this growth in the design.
- **Analytics:** Consider incorporating a way to track user interactions with the Navbar. This data can be invaluable for understanding how users navigate your application and can inform future design decisions.
- **Documentation:** It would be beneficial to include both technical documentation (for developers) and user-facing documentation (like a help guide or FAQ).

**Note:**

- The estimate for this is 4 days

**Comment by kamalzrein** [comment]
Navbar design can be checked here : 

https://drive.google.com/file/d/109X757fnL4cEub1bkctG6DqYspQmYN3J/view?usp=sharing
