### ISSUE TITLE
11 - CI Set Up Documentation

### ISSUE THREAD

**Issue by Juanan-design** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#14]

**Comment by ralphgregorio** [comment]
As a group performed a tutorial, full recorded video explanation here: https://drive.google.com/file/d/1UAYqCBXRLoIy7WQUzr1Kg1oIkBrUJZgL/view

Doc is explained here: https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-3/wiki/ID-0
