### ISSUE TITLE
Create a delete Api so we can delete files

### ISSUE THREAD

**Issue by cameronbeattie306** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#161]
The delete hook currently has no functionality because the BEAP backend does not have a route associated with deleting a file.

**Comment by mpk467** [comment]
deleting files from the user's view (but not from the backend) requires an additional column in the database. uncertain if this feature is needed. ticket closed for now, must ask stakeholder in Wednesday meeting for further clarification
