### ISSUE TITLE
Generalize and combine FitbitController and AppleWatchController

### ISSUE THREAD

**Issue by ralphgregorio** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#165]
Currently FitbitController and AppleWatchController are almost exact copies of each other with minor differences.

For example, they have the same routes that does the same functions the only difference being the services called are different but they have the same methods.

**Tech AC:**
- We should also create a common interface/abstract class (whichever one you think is more fit) for FitbitService and AppleWatchService and implement in each respective service, this interface should contain the same public and protected methods they both share 
- After you create the interface, make sure you create a UML Class Diagram for your changes relating the interface and the FitbitService and ApplewatchService.
- Combine FitbitController and AppleWatchController into one Controller, and modify the routes to accept the type based on which service we want to invoke. For example we have /applewatch/upload and /fitbit/upload. We can then do /{type}/upload instead
- In our new generalized controller, make sure to call the correct service based on the type received.
    - I'll leave it up to you how you want to do this. 
- Make sure you create unit tests for all the new files and files you modified!
- Make sure you test the frontend to make sure you did not break anything!

- [x] create service interface with pre-post conditions

- [x] UML class diagram for the changes in services

- [x] combine/generalize controller

- [x] unit tests

**Comment by cameronbeattie306** [comment]
https://drive.google.com/file/d/1JXAltysCvhr7R4v6xLhPjXcvj_2pNqe-/view?usp=sharing
