### ISSUE TITLE
14 - Figure out how the authentication works and files go 

### ISSUE THREAD

**Issue by Juanan-design** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#17]
How does the authentication work right now? Report findings on the ticket/issue

**Comment by ralphgregorio** [comment]
Related to [Issue 18](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-3/issues/18)

**Comment by ralphgregorio** [comment]
The authentication is currently manually handled in java springMVC backend that is provided with the project.

The associated tables are 

`tbl_login_user`
`tbl_access_group`
`tbl_role`
`tbl_user`
`tbl_user_tbl_access_group`
`tbl_user_tbl_raw_data`
`tbl_user_tbl_role`
`tbl_incorrect_logins`

**Comment by ralphgregorio** [comment]
The files are parsed in the backend and associated data is stored in its respective tables for processing/predicting.

- Predicted Data is stored in `tbl_processed_data`
- Processed Data is stored in `tbl_predicted_data`
- Raw Data is stored in `tbl_raw_data`
