### ISSUE TITLE
Use the profiler in our code

### ISSUE THREAD

**Issue by Juanan-design** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#177]
Use the Profiler to go through our code (ID3 version) and create a report with the results of places where there are a bottleneck of performance, or if the system is running correctly.

**Comment by Juanan-design** [comment]
This refers to using the profiler in the frontend code

**Comment by DanBenesh** [comment]
I have completed profiling our front end. The Document can be found here:[Profiling Front end]( https://docs.google.com/document/d/1Lyzte6osb9Jz4hRPB_4IDFDF3BhRXItlJ1QOG_8c1dU/edit?usp=sharing). Please review and let me know if changes should be made. Thanks

**Comment by Juanan-design** [comment]
Looks really good to me!
