### ISSUE TITLE
Perform Smoke Test On Uploading Files

### ISSUE THREAD

**Issue by Juanan-design** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#178]
Perform a Smoke Test regarding the process of uploading Files in out app. Record the test and the results in the General Test Matrix.

**Comment by ralphgregorio** [comment]
Example of mocking an api

https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-3/blob/master/frontend/tests_end2end/util/setupMockLogin.ts

**Comment by Juanan-design** [comment]
Smoke test may be done manually or automated with playwright ( would need to mock data)
