### ISSUE TITLE
 15 - Figure out the tables

### ISSUE THREAD

**Issue by Juanan-design** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#18]
What are the tables used, its dependencies. Report findings on the ticket/issue

**Comment by ralphgregorio** [comment]
![beapEngine_tableRelationships](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-3/assets/59103488/77eb8385-1add-4ca2-a073-9afb2292bd9f)
