### ISSUE TITLE
Complete implementation of Logout page

### ISSUE THREAD

**Issue by glenntanjoh** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#183]
Let clicking the logout button on the navbar logout securely end the session and redirect the user to the homepage

**Comment by ralphgregorio** [comment]
Logout hook implemented here

https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-3/blob/master/frontend/src/shared/hooks/useLogout.ts
