### ISSUE TITLE
Research a Profiler for Java

### ISSUE THREAD

**Issue by Juanan-design** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#186]
Research viable Profilers to be used on the Backend

**Comment by redwing14e** [comment]
After some initial research found [Prefix](https://stackify.com/prefix/).  
It looks good but seems to only have Windows support for Java profiling and there might be more issues when trying to integrate into our build.  
One thing that is nice is that there seems to be a free version where other popular profilers seem to not have free versions

**Comment by redwing14e** [comment]
Probably the best option, after some discussion, is to just use the profiler built into Intellij
