### ISSUE TITLE
16-Figure out how R Library is connected with the app

### ISSUE THREAD

**Issue by Juanan-design** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#19]
How does it process the files and predict. Where does it call it? Where? When? How? Do we need to do anything? Report findings on the ticket/issue

**Comment by ralphgregorio** [comment]
For our provided backend, we have to supply the path in the environment variables in postgresql.properties and r_repo.properties files.

Make tomcat as the RCode path directory owner (after tomcat user being created and tomcat is installed)

This would be r_repo.path={path-to-R-repo}

Also have to make sure the directories exists on the server

r_repo.path/zips
r_repo.path/tmp
r_repo.path/fitbit/data/output
r_repo.path/fitbit/data/raw
r_repo.path/applewatch/data/output
r_repo.path/applewatch/data/raw
