### ISSUE TITLE
Create User Profile Page API Routes

### ISSUE THREAD

**Issue by kamalzrein** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#198]
Create a profile page where the user can:

1- Check their information
2- Update their information
3- Delete their account
   3.1- Data deletion
   3.2- Short-term data retention (?)

- [x] GET route that returns first name, last name, and username. Route: "/user"
- [x] Create a new POST route that lets a user update password. Route: "/password"
- [x] Create hard DELETE of all data relating to the user and delete account
- [x] Create DELETE all data made (and uploaded?) to the webapp

**Comment by ralphgregorio** [comment]
Backend Work Involved:

Tech AC:
- Create a new GET route that returns user first name, last name, and username.
      - This should live in the UserController
      - Do a check to make sure that the current session is valid, and the person making the request is the same user as the current session
- Create a new POST route that lets a user update password
      -      - This should live in the UserController
- Create two DELETE routes for the user
      -  HARD DELETE EVERYTHING RELATED TO THE USER(Account information and data made on the web app). Stakeholder confirmation in notion.
      - Delete just the data made on the webapp
 - Make sure to test

**Comment by mpk467** [comment]
If 3.2- Short-term data retention (?) requirement is unclear, this needs to be clarified in today's stakeholder meeting

**Comment by mpk467** [comment]
{{baseUrl}}/user GET request working with postman
![image](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-3/assets/156002369/c2b9c616-85d3-4a10-857d-158f1786f110)

**Comment by ralphgregorio** [comment]
branched was merged as part of https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-3/pull/290
