### ISSUE TITLE
Research a tool to perform load and Stress testing and carry them out

### ISSUE THREAD

**Issue by Juanan-design** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#247]
Only create a document with the steps you have taken and how you set up the tests.

**Comment by mpk467** [comment]
the oculus team encountered an issue with large file sizes and react hooks (react . It is my understanding that we use the useState() hook to store file data in browser before uploading it

`    const [filesPerYear, setFilesPerYear] = useState<{
        [years: string]: FileWithPath[];
    }>({});`
    
   it would be worthwhile talking with the oculus team to learn more about this limitation and figuring out if this will be a limiting factor. if so we could consider a workaround like limiting the total file size that can be uploaded at once

**Comment by Juanan-design** [comment]
Deadline: Tuesday 26 March
