### ISSUE TITLE
Login/Sign Up Page finishing touches

### ISSUE THREAD

**Issue by glenntanjoh** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#252]
There are some more issues I found with the Login and Sign Up pages:

- [x]  Error handling for invalid user actions. We need messages to tell the user why they are not being signed in(E.g. Login failed. Incorrect username or password e.t.c.)

- [x] Make the text slider automatic(User shouldn’t have to click the arrows for the next text to be displayed. Cursor needs to change as well to signify that the arrow is clickable.

- [x] Make the page responsive(Run media queries to adapt the pages according to screen size being browsed on)

- [x] Make homepage accessible on the Login/SignUpPage

- [x] Attach a clickable privacy policy link to the “Agree to terms and privacy policy” text for user to read before they check the box to sign up.

- [x]  Add Jest tests to reflect changes

- [x] Collect client key from stakeholder and enable google functionality(Not implement it)

- [x] Replace console logs with rollbar

- [x] Add runtime assertions

- [x] Brush up on the overall styles and bring them as close to design as possible (Watch out for font and colours)

- [x]  After authentication, redirect user to file upload page, sign up page should take you to login if already have an account, already logged in users should not be able to see login and sign up pages, they should instead be redirected to File Upload page when they click on the login or sign up button

- [x]  Hide Forget password

- [x]  Fix google Login display

**Comment by DanBenesh** [comment]
I am having trouble making the text slider automatically change. I have made a clickable link to the privacy policy, I don't believe users should have to check to agree to the privacy policy every time they sign in. This should checked off when making their account. Still working on getting the error messages to work

**Comment by glenntanjoh** [comment]
All done here
