### ISSUE TITLE
Processed Data Page finishing touches

### ISSUE THREAD

**Issue by glenntanjoh** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#253]
- [x]  Add Progress Bar to implementation. blocked by #256 

- [ ]  The page is not centered properly. Currently, it doesn't align with the navbar like the other pages. Please align this and you can use the centered navbar links as a guide.

- [ ]  Add Jest tests to reflect changes

- [ ]  Make the page responsive(Run media queries to adapt the pages according to screen size being browsed on)

- [ ]  Adding runtime assertions

- [x]  Provide user feedback error messages for when things go wrong e.g. Prediction Failed. Please try again(later)

- [ ]  Brush up on styles. Bring it as close to the design as possible (Watch out for font and colours)

**Comment by cameronbeattie306** [comment]
I have added the progress bar, and snack bar to the processed data page.
