### ISSUE TITLE
25-Predicted Data Page

### ISSUE THREAD

**Issue by ArdalanAskarian** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#27]
- Implement the basic UI
- Refer to old repository
- Make sure you write unit tests and make sure you get approval before merging
- Estimate: 2 Days

**Comment by DanBenesh** [comment]
This issue was resolved by a previous pull request [https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-3/pull/81](url)
