### ISSUE TITLE
34-Setup Git Branch Protection Rules

### ISSUE THREAD

**Issue by ralphgregorio** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#34]
Setup rules for protecting branches from unsafe merges

**Comment by ralphgregorio** [comment]
Rules to be implemented:
- Enforcing 1 approval before you can merge in development/feature branches
- Enforcing 2 approvals for merges to master and release
- Enforcing CI checks to pass before you can merge
- Require branches to be up to date before merging
- Locking out direct committing to masters

**Comment by ArdalanAskarian** [comment]
Everything is set up and done!
