### ISSUE TITLE
Connect the backend with the R repository

### ISSUE THREAD

**Issue by ralphgregorio** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#63]
This issue is **BLOCKED** by https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-3/issues/62
Try to connect the backend to use the R directory

**Comment by mpk467** [comment]
Dev will help with this ticket after design tickets are complete

**Comment by ralphgregorio** [comment]
Done at #89
