### ISSUE TITLE
File Upload Page Functionality

### ISSUE THREAD

**Issue by glenntanjoh** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-3#75]
Issue **blocked** by #66 
Implement file upload functionality on the File Upload Page. Users should be able to select files (Fitbit or Apple Watch data) and initiate the upload. After that, users should be able to see the files uploaded and select which of them they want to process.
Broken down tasks:
Handle user file selection and initiation of the upload (Since the component seems to have been created already)
Handle fetch and post requests to display files uploaded and files sent to the process page
If upload fails -> have contingency rollback plan

Note:
Please ensure extensive use of comments, Jest tests, error handling and validation where applicable.
The estimate for this is 2 days

**Comment by mpk467** [comment]
```[tasklist]
### My tasks
- [ ] react call upload function on file selection
- [ ] upload file to server
- [ ] add error handling
- [ ] add file validation
```

**Comment by mpk467** [comment]
### Issue Tasks
- [x] add isActive webhooks
- [x] add upload option "from my computer"
- [x] add upload button
- [x] list accepted files
- [ ] provide state diagram for component interaction
- [ ] add file types (Fitbit and Apple watch)
- [ ] preliminary parse and zip (pre-processing)
- [ ] add error handling
- [ ] add file validation
- [ ] add unit tests

**Comment by mpk467** [comment]
post request send to API //http://localhost:8080/rest/beapengine/fitbit

**Comment by mpk467** [comment]
there are issues uploading to the server. This ticket will only include describing the interactions between users, components, and file selection.
